# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Weekly Sunday(0) at 3 minutes pas 5 am.
  schedule:
  - cron: '3 5 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Selecting the xml branch
      - uses: actions/checkout@v3
        with:
          ref: xml

      # Run the create RSS Script
      - name: Create the feed with a PowerShell script
        # You may pin to the exact commit or the version.
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: ./MakeFeed.ps1

      # Commit against XML branch
      - name: Commit updated feed.rss
        run: |
          git config user.name 'Github Build Service'
          git config user.email 'rolf.eleveld@outlook.com'
          git commit -m "Updated feed.rss"
          git push
